- hosts: all
  become: true
  tasks:
  - name: Update packages
    apt:
      update_cache: yes
      upgrade: dist
  - name: Add an Apt signing key, uses whichever key is at the URL
    apt_key:
      url: "https://download.docker.com/linux/ubuntu/gpg"
      state: present
  - name: Add docker registry
    apt_repository: 
      repo: 'deb https://download.docker.com/linux/ubuntu xenial stable' 
      state: present
  - name: ensure docker and dependencies are installed
    apt: 
      name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
      state: present
  - name: ensure docker config file exists
    copy:
      content: "{}"
      dest: /etc/docker/daemon.json
      force: no
      group: root
      owner: root
      mode: 0600
  - name: load config from daemon.json
    include_vars:
      file: /etc/docker/daemon.json
      name: imported_json
  - name: add log-driver if it is not presented
    set_fact:
      imported_json: "{{ imported_json | combine({ 'log-driver': 'syslog' }) }}"
  - name: update daemon.json
    copy: 
      content: "{{ imported_json | to_nice_json }}" 
      dest: /etc/docker/daemon.json
    notify:
    - restart docker
  - name: ensure docker is running
    service:
      name: docker
      state: started
  
  handlers:
    - name: restart docker
      service:
        name: docker
        state: restarted
